/*
 Navicat Premium Data Transfer

 Source Server         : localhost_5432
 Source Server Type    : PostgreSQL
 Source Server Version : 130012 (130012)
 Source Host           : localhost:5432
 Source Catalog        : employee_db
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 130012 (130012)
 File Encoding         : 65001

 Date: 22/08/2023 16:00:19
*/


-- ----------------------------
-- Sequence structure for employee_nik_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."employee_nik_seq";
CREATE SEQUENCE "public"."employee_nik_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Table structure for employee
-- ----------------------------
DROP TABLE IF EXISTS "public"."employee";
CREATE TABLE "public"."employee" (
  "nik" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "employee_age" int4,
  "employee_name" varchar(255) COLLATE "pg_catalog"."default",
  "employee_salary" int4
)
;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."employee_nik_seq"
OWNED BY "public"."employee"."nik";
SELECT setval('"public"."employee_nik_seq"', 1, true);

-- ----------------------------
-- Primary Key structure for table employee
-- ----------------------------
ALTER TABLE "public"."employee" ADD CONSTRAINT "employee_pkey" PRIMARY KEY ("nik");
